name: Deploy to GitHub Releases for Windows

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Windows Release
    runs-on: windows-latest
    steps:
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -e .
    - name: Build windows executable
      working-directory: ./build-recipes
      run: |
        pip install -r win_build_requirements.txt
        pyinstaller -y --log-level=WARN win_DCKit.spec
        # Run the binary (the most simple test)
        dist\\DCKit\\DCKit.exe --version
        python win_make_iss.py
        ISCC.exe /Q win_dckit.iss
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        draft: true
        automatic_release_tag: "${{ env.RELEASE_VERSION }}"
        title: "DCKit ${{ env.RELEASE_VERSION }}"
        files: |
          ./build-recipes/Output/*.exe
