name: Deploy to GitHub Releases for macOS

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: macOS Release
    runs-on: macos-latest
    steps:
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -e .
    - name: Build macOS app
      working-directory: ./build-recipes
      run: |
        bash ./macos_build_app.sh DCKit ${{ env.RELEASE_VERSION }}
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        draft: true
        automatic_release_tag: "${{ env.RELEASE_VERSION }}"
        title: "DCKit ${{ env.RELEASE_VERSION }}"
        files: |
          ./build-recipes/dist/*.dmg
          ./build-recipes/dist/*.pkg
